us_cities = [
    "New York City, New York",
    "Los Angeles, California",
    "Chicago, Illinois",
    "Houston, Texas",
    "Phoenix, Arizona",
    "Philadelphia, Pennsylvania",
    "San Antonio, Texas",
    "San Diego, California",
    "Dallas, Texas",
    "San Jose, California",
    "Austin, Texas",
    "Jacksonville, Florida",
    "Fort Worth, Texas",
    "Columbus, Ohio",
    "San Francisco, California",
    "Charlotte, North Carolina",
    "Indianapolis, Indiana",
    "Seattle, Washington",
    "Denver, Colorado",
    "Washington, D.C.",
    "Boston, Massachusetts",
    "El Paso, Texas",
    "Nashville, Tennessee",
    "Detroit, Michigan",
    "Portland, Oregon",
    "Memphis, Tennessee",
    "Oklahoma City, Oklahoma",
    "Las Vegas, Nevada",
    "Louisville, Kentucky",
    "Baltimore, Maryland",
    "Milwaukee, Wisconsin",
    "Albuquerque, New Mexico",
    "Tucson, Arizona",
    "Fresno, California",
    "Sacramento, California",
    "Kansas City, Missouri",
    "Long Beach, California",
    "Mesa, Arizona",
    "Atlanta, Georgia",
    "Colorado Springs, Colorado",
    "Raleigh, North Carolina",
    "Miami, Florida",
    "Virginia Beach, Virginia",
    "Omaha, Nebraska",
    "Oakland, California",
    "Minneapolis, Minnesota",
    "Tulsa, Oklahoma",
    "Wichita, Kansas",
    "New Orleans, Louisiana",
    "Arlington, Texas",
    "Cleveland, Ohio",
    "Tampa, Florida",
]
